### ISSUE TITLE
Crashes when an exception is immediately thrown in _ready on game launch

### ISSUE THREAD

**Issue by chrisanicolaou** [xibbon/XogotIssues#8] opened 2024-11-13 21:57 UTC
**System information**
iPad Air 13-inch M2
iPadOS 18.1 (22B83)

**Description**
Exceptions that would normally pause project execution will cause a crash when thrown immediately as the game launches

**Reproduction steps**
1. Create a new project
2. Create a scene and attach a script
3. Force an exception in `_ready`, e.g:
```
@export var reference: PackedScene

func _ready() -> void:
    reference.instantiate()
```
4. Save the script & scene, and run the game.
5. The app will crash.
6. Add the following line before the exception:
`await get_tree().process_frame`
7. The app will now correctly pause on exception.

**Comment by migueldeicaza** [comment] 2024-11-14 18:28
What do you mean by crash in this case, I could not reproduce it.

But it did trigger an infinite loop, which I suspect when not attached to a debugger would eventually crash, is that what you observed?   I have a fix for this and should be in the testflight shortly.

**Comment by chrisanicolaou** [comment] 2024-11-14 19:19
> But it did trigger an infinite loop, which I suspect when not attached to a debugger would eventually crash, is that what you observed?

No - the above example wouldn't trigger an infinite loop. I've also just re-tested and confirmed it's still occurring in the latest release.

[Here is a video](https://streamable.com/hgdlmu) of my latest test of the reproducible steps; I've used Resource instead of PackedScene, but any nullable type will see the same results. I'm leaving the reference as null (i.e not assigning in the inspector).

Let me know if this video is clear enough or if you need further details.

**Comment by migueldeicaza** [comment] 2024-11-25 20:58
Thank you, I can reproduce and we are tracking. #717

**Comment by migueldeicaza** [comment] 2024-12-17 02:44
Fixed on November 29th.

**Closed as completed by migueldeicaza** 2024-12-17 02:44 UTC
Labels: tracking
